title: "Jeanette Jordan — GRC Portfolio"
description: "Sample Governance, Risk & Compliance portfolio showcasing Risk Register, Vendor Questionnaire, and Security Policies."
theme: jekyll-theme-cayman
