# ===========================
# Jeanette Jordan — GRC Portfolio Configuration
# ===========================

title: "Jeanette Jordan — GRC Portfolio"
tagline: "Federal Cybersecurity Leader | NIST RMF | Microsoft 365 & Azure Security Compliance"
description: "Governance, Risk & Compliance portfolio demonstrating core documentation: Risk Register, Vendor Security Questionnaire, and Security Policies aligned with NIST and DoD frameworks."

# ---------------------------
# Theme and Layout
# ---------------------------
theme: jekyll-theme-cayman
show_downloads: false

# ---------------------------
# Navigation (Top Banner Links)
# ---------------------------
nav:
  - name: "Home"
    link: index.md
  - name: "Risk Register"
    link: 01_risk_register/README.md
  - name: "Vendor Questionnaire"
    link: 02_vendor_questionnaire/README.md
  - name: "Policies"
    link: 03_policies/README.md

# ---------------------------
# Footer (Displayed on Every Page)
# ---------------------------
footer_content: |
  ---
  **Contact:** [JeanetteD_Jordan@outlook.com](mailto:JeanetteD_Jordan@outlook.com)  
  **GitHub:** [github.com/JJordan1983](https://github.com/JJordan1983)  
  **LinkedIn:** [linkedin.com/in/jeanette-jordan](https://linkedin.com/in/jeanette-jordan)  
  **Location:** Stafford, VA  
  Licensed under the [MIT License](LICENSE)

# ---------------------------
# GitHub Metadata
# ---------------------------
github:
  is_project_page: true
  repository_url: https://github.com/JJordan1983/grc_portfolio

# ---------------------------
# Markdown Rendering Settings
# ---------------------------
markdown: kramdown
kramdown:
  input: GFM


