# ===========================
# Jeanette Jordan — GRC Portfolio Configuration
# ===========================

title: "Jeanette Jordan — GRC Portfolio"
tagline: "Federal Cybersecurity Leader | NIST RMF | Microsoft 365 & Azure Security Compliance"
description: >
  Governance, Risk & Compliance portfolio demonstrating documentation and control implementation
  aligned with FedRAMP Moderate, NIST SP 800-53 Rev. 5, and DoD cybersecurity frameworks.

# ---------------------------
# Theme and Layout
# ---------------------------
theme: jekyll-theme-cayman
show_downloads: false

# Optional color mode support (for modern browsers)
minima:
  skin: auto

# ---------------------------
# Navigation (Top Banner Links)
# ---------------------------
nav:
  - name: "Home"
    link: index.md
  - name: "Risk Register"
    link: 01_risk_register/index.md
  - name: "Vendor Questionnaire"
    link: 02_vendor_questionnaire/index.md
  - name: "Policies"
    link: 03_policies/index.md
  - name: "Incident Response"
    link: 04_incident_response/README.md
  - name: "Continuous Monitoring"
    link: 05_continuous_monitoring/README.md
  - name: "Data Classification"
    link: 06_data_classification/README.md
  - name: "Vuln Mgmt"
    link: 07_vulnerability_management/README.md
  - name: "AI Compliance"
    link: 08_ai_compliance/README.md

# ---------------------------
# Footer (Displayed on Every Page)
# ---------------------------
footer_content: |
  ---
  **Contact:** [JeanetteD_Jordan@outlook.com](mailto:JeanetteD_Jordan@outlook.com)  
  **GitHub:** [github.com/JJordan1983](https://github.com/JJordan1983)  
  **LinkedIn:** [linkedin.com/in/jeanette-jordan](https://linkedin.com/in/jeanette-jordan)  
  **Location:** Stafford, VA  
  Licensed under the [MIT License](LICENSE)

# ---------------------------
# GitHub Metadata
# ---------------------------
github:
  is_project_page: true
  repository_url: https://github.com/JJordan1983/grc_portfolio

# ---------------------------
# Plugins for SEO and Sitemap
# ---------------------------
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# ---------------------------
# Markdown Rendering Settings
# ---------------------------
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false

# ---------------------------
# Exclusions (Optional)
# ---------------------------
exclude:
  - "*.zip"
  - "README_local.md"
  - "NAV_NOTES_FOR_CONFIG_YML.md"

# ---------------------------
# Author Information
# ---------------------------
author:
  name: "Jeanette Jordan"
  email: "JeanetteD_Jordan@outlook.com"
  location: "Stafford, VA"
  organization: "APJ Enterprise LLC"
